# Generated by Django 3.0.4 on 2022-02-08 09:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.SmallIntegerField(choices=[('', 'Select'), (1, 'As Admin'), (2, 'User')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('tel_number', models.CharField(blank=True, max_length=11, null=True)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode should have exactly 6 digits.', regex='^[0-9]{6}$')])),
                ('city', models.CharField(max_length=40)),
                ('state', models.SmallIntegerField(choices=[('', 'Select'), (1, 'Andaman And Nicobar Islands'), (2, 'Andhra Pradesh'), (3, 'Arunachal Pradesh'), (4, 'Assam'), (5, 'Bihar'), (6, 'Chandigarh'), (7, 'Chhattisgarh'), (8, 'Dadra And Nagar Haveli'), (9, 'Daman And Diu'), (10, 'Delhi'), (11, 'Goa'), (12, 'Gujarat'), (13, 'Haryana'), (14, 'Himachal Pradesh'), (15, 'Jammu And Kashmir'), (16, 'Jharkhand'), (17, 'Karnataka'), (18, 'Kerala'), (19, 'Ladakh'), (20, 'Lakshadweep'), (21, 'Madhya Pradesh'), (22, 'Maharashtra'), (23, 'Manipur'), (24, 'Meghalaya'), (25, 'Mizoram'), (26, 'Nagaland'), (27, 'Orissa'), (28, 'Pondicherry'), (29, 'Punjab'), (30, 'Rajasthan'), (31, 'Sikkim'), (32, 'Tamil Nadu'), (33, 'Telangana'), (34, 'Tripura'), (35, 'Uttar Pradesh'), (36, 'Uttarakhand'), (37, 'West Bengal')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
