# Generated by Django 3.0.4 on 2022-02-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20220214_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_position',
            field=models.CharField(default='', max_length=40),
        ),
    ]
