# Generated by Django 3.0.4 on 2022-04-09 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0006_auto_20220226_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_view', models.BooleanField(default=False)),
                ('product_create', models.BooleanField(default=False)),
                ('product_delete', models.BooleanField(default=False)),
                ('product_update', models.BooleanField(default=False)),
                ('category_view', models.BooleanField(default=False)),
                ('category_create', models.BooleanField(default=False)),
                ('category_delete', models.BooleanField(default=False)),
                ('category_update', models.BooleanField(default=False)),
                ('subcategory_view', models.BooleanField(default=False)),
                ('subcategory_create', models.BooleanField(default=False)),
                ('subcategory_delete', models.BooleanField(default=False)),
                ('subcategory_update', models.BooleanField(default=False)),
                ('order_view', models.BooleanField(default=False)),
                ('order_update', models.BooleanField(default=False)),
                ('order_delete', models.BooleanField(default=False)),
                ('self_inquiry_view', models.BooleanField(default=False)),
                ('all_inquiry_view', models.BooleanField(default=False)),
                ('customer_profile_view', models.BooleanField(default=False)),
                ('company_profile_view', models.BooleanField(default=False)),
                ('distributors_profile_view', models.BooleanField(default=False)),
                ('dealer_profile_view', models.BooleanField(default=False)),
                ('serviceagent_profile_view', models.BooleanField(default=False)),
                ('lender_profile_view', models.BooleanField(default=False)),
                ('customer_profile_approve_view', models.BooleanField(default=False)),
                ('company_profile_approve_view', models.BooleanField(default=False)),
                ('distributors_profile_approve_view', models.BooleanField(default=False)),
                ('dealer_profile_approve_view', models.BooleanField(default=False)),
                ('serviceagent_profile_approve_view', models.BooleanField(default=False)),
                ('lender_profile_approve_view', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
