# Generated by Django 3.0.4 on 2022-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateBillImgUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksale_id', models.PositiveIntegerField()),
                ('product_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[('', 'Select'), (1, 'Backoffice'), (2, 'Store'), (3, 'Finance')])),
            ],
        ),
    ]
