# Generated by Django 3.0.4 on 2022-02-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_generatebillimgupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerateBillImgUpload',
        ),
    ]
