# Generated by Django 3.0.4 on 2022-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_profile_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
